#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Single monitor
# bspc monitor -d I II III IV V VI VII VIII IX X

# Multi monitor
bspc monitor DP-2 -d 1 2 3 4
bspc monitor HDMI-1 -d 5
bspc monitor HDMI-2 -d 6 7

bspc config border_width         2
bspc config window_gap          19

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a weechat desktop=^7
bspc rule -a discord desktop=^6
bspc rule -a Firefox desktop=^5

bspc rule -a Lxappearance state=floating follow=on rectangle=1440x900+960+730
bspc rule -a mutt state=floating follow=on rectangle=1440x900+960+730
bspc rule -a Gimp-2.10 state=floating follow=on rectangle=1440x900+960+730
bspc rule -a scratchy sticky=on state=floating rectangle=1440x900+960+730
bspc rule -a htop sticky=on state=floating rectangle=1440x900+960+730
bspc rule -a ncmpcpp sticky=on state=floating rectangle=1440x900+960+730

bspc rule -a Pcmanfm state=floating follow=on


~/.config/bspwm/autostart &
